#!/bin/bash

export PATH="$(dirname $0)"/helpers:$PATH

COMMAND="$1"
case $COMMAND in

  "set-app-password")

    USERNAME=$2
    PASSWORD=$3

    PWDDIR="$BACKUPCONFD"/bitbucket
    PWDFILE="$PWDDIR/$USERNAME"
    GITPWDFILE="$PWDFILE.git"

    mkdir -p "$PWDDIR"
    printf "$PASSWORD" > "$PWDFILE"
    echo "https://$USERNAME:$PASSWORD@bitbucket.org" > "$GITPWDFILE"
    ;;

  "clone-all")

    USERNAME=$2
    
    PWDFILE="$BACKUPCONFD/bitbucket/$USERNAME"
    GITPWDFILE="$PWDFILE.git"

    mapfile -t LINES < <(list-bitbucket-git-repos "$USERNAME" "$PWDFILE")
    for LINE in "${LINES[@]}"
    do
      VALS=($LINE);
      if (( ${#VALS[@]} == 3 )); then
        ROOTD="$BACKUPDATAD/bitbucket/$USERNAME"
        mkdir -p "$ROOTD"
        SLUG=${VALS[0]}
        REPOD="$ROOTD/$SLUG"
        if [ ! -d "$REPOD" ]; then
          echo Creating mirror of $SLUG
          CLONE_URL="${VALS[1]}"
          FETCH_URL="${VALS[2]}"
          git clone --mirror "$CLONE_URL" "$REPOD"
          git --git-dir "$REPOD" remote set-url origin "$FETCH_URL"
          git --git-dir "$REPOD" config credential.helper "store --file $GITPWDFILE"
        else
          echo Updating mirror of $SLUG
          git --git-dir "$REPOD" remote update
        fi
      fi
    done
    ;;

  *)

    echo "Invalid command"
    exit 1
    ;;

esac

