#!/bin/bash

export PATH="$(dirname $0)"/helpers:$PATH

COMMAND="$1"
case $COMMAND in

  "clone-all")

    USERNAME=$2
    mapfile -t LINES < <(list-github-public-repos "$USERNAME")
    for LINE in "${LINES[@]}"
    do
      VALS=($LINE);
      if (( ${#VALS[@]} == 2 )); then
        ROOTD="$BACKUPDATAD/github/$USERNAME"
        mkdir -p "$ROOTD"
        SLUG=${VALS[0]}
        REPOD="$ROOTD/$SLUG"
        if [ ! -d "$REPOD" ]; then
          echo Creating mirror of $SLUG
          CLONE_URL="${VALS[1]}"
          git clone --mirror "$CLONE_URL" "$REPOD"
        else
          echo Updating mirror of $SLUG
          git --git-dir "$REPOD" remote update
        fi
      fi
    done
    ;;

  *)

    echo "Invalid command"
    exit 1
    ;;

esac

