#!/bin/bash

source .environment

COMMAND="$1"
case $COMMAND in

  "copy")

    USER=$2
    YEAR=$3
    REMOTE="drive-$USER"
    echo Using rclone remote $REMOTE
    run-rclone dedupe --stats 0 --dedupe-mode rename "$REMOTE":"Google Photos/$YEAR"
    run-rclone copy --stats 0 --ignore-existing "$REMOTE":"Google Photos/$YEAR" "$BACKUPDATAD/google-photos/$USER/$YEAR"
    ;;

  *)

    echo "Invalid command"
    exit 1
    ;;

esac

