#!/usr/bin/env python3

import sys
import requests

username = sys.argv[1]

api_repo_url = "https://api.github.com/users/{0}/repos".format(username)
response = requests.get(api_repo_url)
response.raise_for_status()
for repo in response.json():
  print("{0} {1}".format(repo['name'], repo['clone_url']))

