#!/bin/bash

mkdir -p "$BACKUPCONFD"
mkdir -p "$BACKUPDATAD"

FLAGS=""
[[ -t 0 ]] && FLAGS="$FLAGS -i"
[[ -t 1 ]] && FLAGS="$FLAGS -t"
docker run $FLAGS --rm --log-driver syslog -v "$BACKUPCONFD"/rclone/.rclone.conf:/root/.rclone.conf -v "$BACKUPDATAD":"$BACKUPDATAD" kevineye/rclone rclone "$@"

