#!/bin/bash

mkdir -p "$BACKUPCONFD"
mkdir -p "$BACKUPDATAD"

FLAGS=""
[[ -t 0 ]] && FLAGS="$FLAGS -i"
[[ -t 1 ]] && FLAGS="$FLAGS -t"
docker run $FLAGS --rm --log-driver syslog -v "$BACKUPCONFD"/rclone:/root -v "$BACKUPDATAD":"$BACKUPDATAD" jacobwgillespie/rclone "$@"

